version: '3.9'
services:
  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq
    restart: always
    ports:
      - 9000:15672
      - 9999:5672
    hostname: stats
    volumes:
      - ./datarbmq:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.5
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host

volumes:
  datarbmq:
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge

