version: '3.9'
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql_service
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./schemas:/var/lib/mysql

volumes:
  schemas: