version: '3.9'
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_service
    restart: always
    ports:
      - 80:80
    volumes: 
      - ./app:/var/www/html
  
  db:
    build: 
      context: ../mysql
      dockerfile: Dockerfile
    container_name: mysql-php
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./schemas:/var/lib/mysql

volumes:
  app:
  schemas: