version: '3.9'
services:
  mongodb:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mongodb_service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

volumes:
  mongo: